GET http://localhost:3030/premio

###
POST http://localhost:3030/premio
Content-Type: application/json
    
    {
        "nombre": "Viaje a la playa",
        "descripcion": "Gano un viajesito a la playa"
    }

###

PUT http://localhost:3030/premio/1
Content-Type: application/json
    
    {
        "nombre": "Viaje a mi casa",
        "descripcion": "Gano un viajesito a mi casa"
    }

###
DELETE http://localhost:3030/premio/1



